version: '3.3'
services:
  noldaga-db:
    platform: linux/amd64
    image: bibimbap/noldaga-db
    build: DB
    ports:
      - "5432:5432"
    volumes:
      - ~/postgres-data:/var/lib/postgresql/data
    restart: always
  noldaga-server:
    platform: linux/amd64
    image: bibimbap/noldaga-server
    build: server
    ports:
      - "8001:8001"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
  noldaga-client:
    platform: linux/amd64
    image: bibimbap/noldaga-client
    build: client
    ports:
      - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /usr/src/cert:/usr/src/app/cert
    restart: always