version: '3.3'
services:
  noldaga-db:
    image: bibimbap/noldaga-db
    ports:
      - "5432:5432"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ~/postgres-data:/var/lib/postgresql/data
    restart: always
  noldaga-server:
    image: bibimbap/noldaga-server
    ports:
      - "8001:8001"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /usr/src/static/server_logs:/usr/src/app/logs
      - /usr/src/static/thumbnail:/usr/src/app/thumbnail
    restart: always
  noldaga-client:
    image: bibimbap/noldaga-client
    ports:
      - "80:80"
      - "443:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /usr/src/cert:/usr/src/app/cert
      - /usr/src/static/object_files:/usr/src/app/static/object_files
    restart: always